### ISSUE TITLE
Knuckles JUMP maintained flying issue

### ISSUE THREAD

**Issue by Catarax** [cheatfreak47/SRUpdater#1]
Hello,

While flying with Knuckles, If I maintain the space bar, i can't move to left or right, I have to release.
However on Sega Saturn, there is no issue, you can keep the jump button to move during the fly.

It looks buggy on PC, using the 2004 release by default.

**Comment by cheatfreak47** [comment]
This is a problem with your keyboard, I can jump and fly/glide just fine.
You should remap your keyboard keys in the game's settings menu.

**Comment by cheatfreak47** [comment]
You should also try using a gamepad, which I've also used and also works perfectly fine.
