### ISSUE TITLE
install unsuccessful , help

### ISSUE THREAD

**Issue by asdfj2381k** [cheatfreak47/SRUpdater#2]
![image](https://user-images.githubusercontent.com/56584082/82166946-bb484180-98ec-11ea-908d-539ac3690f26.png)

i think the Path is right..

**Comment by asdfj2381k** [comment]
Oh..

I see the problem, it's an updater, not a full installation file.

But it's been 20 years and I don't seem to have access to the full installation package.

**Comment by cheatfreak47** [comment]
this is the intended behaviour
