### ISSUE TITLE
mmmm not able to actually play?

### ISSUE THREAD

**Issue by neofeo** [cheatfreak47/SRUpdater#3]
HI guys!! awesome project..
I am testing it on Linux, with wine... on ARM. yeah, long story.
The thing is, unlike the original version, this one doesnt allow me tu play any mode.
I dont know the game, just a tester of the emulator. how is this possible. I can only go to options. 

best regards.

**Comment by cheatfreak47** [comment]
This is not a tested or supported use case for any of this.

**Comment by cheatfreak47** [comment]
that said, it sounds like the cd check isn't being bypassed, which is something that Sonic R Mod Loader does by default
sounds like however you're loading the game it's not loading with the mod loader correctly
