### ISSUE TITLE
Screen flickers during screen transitions on resolutions above 1080p

### ISSUE THREAD

**Issue by ViperAcidZX** [cheatfreak47/SRUpdater#4]
I seem to be having this strange problem where the game's oval fade out/in transitions causes the screen to flicker whenever I'm playing the game on resolutions above 1920x1080 (in my case 3840x2160 since my previous 1080p TV broke down last year).

**Comment by cheatfreak47** [comment]
Yeah I've noticed this too actually, unfortunately this is the wrong place for an issue report (this is an issue with either the mod loader or the game itself)

This repo is for Sonic R Updater, which is just the installer itself.

Sonic R was not meant to be ran in even 1080p, let alone 4K, it just so happens that things start to break at around 4K.

Anyway, my only suggestion is to lower the resolution. The flicker doesn't seem to happen at 1440p (2560x1440) last I checked.

**Comment by cheatfreak47** [comment]
Also worth noting that 4K is a perfect integer scale of 1080p, which would also look just fine on your 4K screen, so running the game at 1080p would also be a good option.

**Comment by ViperAcidZX** [comment]
Is it possible to use the mod loader renamed as something else (e.g. dsound.dll) while using something like dgVoodoo2 instead to trick the game into running higher resolutions above 1080p to circumvent the issue?

**Comment by cheatfreak47** [comment]
As far as I know, that isn't currently possible. Also I don't think dgVoodoo2 even works with the base 2004 port of Sonic R.
